apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vodici
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: referendumski-aktivator-referendum-dostojna-smrt-2025
    newName: rg.fr-par.scw.cloud/djnd/referendumski-aktivator-referendum-dostojna-smrt-2025
    newTag: '6c38a5a40fc1013b47fe018d4f389c2dd3e49212'
