apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vodici
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: referendumski-aktivator-referendum-dostojna-smrt-2025
    newName: rg.fr-par.scw.cloud/djnd/referendumski-aktivator-referendum-dostojna-smrt-2025
    newTag: 'd942772b2ab28cf88785a1df30611270f35fde4e'
